from bs4 import BeautifulSoup

# <p> tag with the following CSS classes will be ignored
EXCLUDED_P_CLASS = {'top_nav', 'nav'}


# extract the plain text content of html page
# specific to the HTML format generated by Adobe Acrobat 2015 DC
def extract_plain_text(html_path):
    result = ''
    with open(html_path, 'r') as file:

        # get the list of <p> tags
        soup = BeautifulSoup(file.read(), 'html.parser')
        tags = soup.find_all('p')

        for tag in tags:
            try:
                # skip the current tag if it has a CSS class in the "exclude" list
                if tag['class'][0] in EXCLUDED_P_CLASS:
                    continue
            except KeyError:
                'do nothing'

            # append the content of this tag in a new line
            result += (''.join(tag.findAll(text=True)) + '\n')

    return result
